name: Compilar APK Animado

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Configurar Java (Necesario para Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 4. Configurar SDK de Android Oficial
        uses: android-actions/setup-android@v3

      - name: 5. Instalar Cython y Buildozer en Python
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: 6. Ejecutar compilador Buildozer
        run: |
          buildozer android debug

      - name: 7. Guardar APK en GitHub para descargar
        uses: actions/upload-artifact@v4
        with:
          name: LioApp-Instalador
          path: bin/*.apk
